# Trigger manually:
# curl -XPOST -u "username:access-token" -H "Accept: application/vnd.github.v3+json" -H "Content-Type: application/json" https://api.github.com/repos/sequelize/website/dispatches --data '{"event_type":"Build website"}'

name: Website production build
on:
  repository_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn lint-no-fix
      - run: yarn typecheck
      - run: yarn sync
      - run: yarn build
      - name: Prepare Netlify dependencies
        run: npm install netlify-cli -g
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: sequelize-site
        run: netlify deploy --dir build --prod --message '${{ github.event.commits[0].message }}'
